out_dir: /home/reza/research/results/Graphormer/graphormer-bace-finetune
metric_best: auc
accelerator: cpu
devices: 1
wandb:
  use: False
  project: bace
dataset:
  cache_load: true
  cache_save: true
  dir: /home/reza/research/data/GraphGPS/
  format: OGB
  name: ogbg-molhiv
  split_mode: cv-stratifiedkfold-5
  split_dir: /home/reza/research/data/GraphGPS/splits/
  task: graph
  task_type: classification
  transductive: False
  node_encoder: True
  node_encoder_name:  LinearNode+GraphormerBias
  node_encoder_num_types: 101
  node_encoder_bn: False
  edge_encoder: False
  edge_encoder_name: LinearBond
  edge_encoder_num_types: 14
  edge_encoder_bn: False
posenc_GraphormerBias:
  enable: True
  node_degrees_only: False
  num_spatial_types: 20
  num_in_degrees: 64
  num_out_degrees: 64
#pretrained:
#  dir: /home/reza/research/results/GraphGPS/pretrained/pcqm4m-GPS+RWSE.deep
#  reset_prediction_head: False
train:
  auto_resume: false
  mode: custom
  batch_size: 32
  eval_period: 1
  ckpt_period: 100
  ckpt_best: true
model:
  type: Graphormer
  loss_fun: cross_entropy
  edge_decoding: dot
  graph_pooling: graph_token
prefix:
  enable: False
  prefix_projection: False
  pre_seq_len: 10
graphormer:
  num_layers: 12
  num_heads: 32
  embed_dim: 768
  dropout: 0.0
  attention_dropout: 0.1
  mlp_dropout: 0.1
  input_dropout: 0.1
gnn:
  head: graphormer_graph
  layers_pre_mp: 0
  layers_post_mp: 3  # Not used when `gnn.head: san_graph`
  dim_inner: 768  # `gt.dim_hidden` must match `gnn.dim_inner`
  batchnorm: True
  act: relu
  dropout: 0.0
  agg: mean
  normalize_adj: False
optim:
  clip_grad_norm: True
  clip_grad_norm_value: 5.0
  optimizer: adamW
  weight_decay: 0.01
  base_lr: 0.0001 # 0.0002
  max_epoch: 100 # 10000
  scheduler: polynomial_with_warmup
