out_dir: /home/reza/research/results/GraphGPS/gps-pcq-performer-large
metric_best: mae
metric_agg: argmin
accelerator: cuda
devices: 1
wandb:
  use: False
  project: pcqm4m
dataset:
  cache_load: true
  cache_save: true
  dir: /home/reza/research/data/GraphGPS/
  format: OGB
  name: PCQM4Mv2-full
  task: graph
  task_type: regression
  transductive: False
  node_encoder: True
  node_encoder_name: SimpleAtom
  node_encoder_bn: False
  edge_encoder: True
  edge_encoder_name: SimpleBond
  edge_encoder_bn: False
posenc_RWSE:
  enable: True
  kernel:
    times_func: range(1,17)
  model: Linear
  dim_pe: 20
  raw_norm_type: BatchNorm
train:
  mode: custom
  batch_size: 256
  eval_period: 1
  ckpt_best: True
#  ckpt_period: 100
model:
  type: GPSModel
  loss_fun: l1
  graph_pooling: mean
gt:
  layer_type: CustomGatedGCN+Performer
  layers: 12
  n_heads: 16
  dim_hidden: 768  # `gt.dim_hidden` must match `gnn.dim_inner`
  dropout: 0.1
  attn_dropout: 0.1
  layer_norm: False
  batch_norm: True
gnn:
  head: san_graph
  layers_pre_mp: 0
  layers_post_mp: 3  # Not used when `gnn.head: san_graph`
  dim_inner: 768  # `gt.dim_hidden` must match `gnn.dim_inner`
  batchnorm: True
  act: relu
  dropout: 0.0
optim:
  clip_grad_norm: True
  optimizer: adamW
  weight_decay: 0.0
  base_lr: 0.0002
  max_epoch: 150
  scheduler: cosine_with_warmup
  num_warmup_epochs: 10
