out_dir: /home/reza/research/results/GraphGPS/gps-freesolv-prefix
metric_best: auto
accelerator: cuda
devices: 1
wandb:
  use: false
  project: freesolv
dataset:
  cache_load: true
  cache_save: true
  dir: /home/reza/research/data/GraphGPS/
  format: PyG
  name: Moleculenet-Freesolv
  split_mode: cv-kfold-5
  split_dir: /home/reza/research/data/GraphGPS/splits/
  task: graph
  task_type: regression
  transductive: False
  node_encoder: True
  node_encoder_name: Atom+RWSE
  node_encoder_bn: False
  edge_encoder: True
  edge_encoder_name: DummyEdge
  edge_encoder_bn: False
posenc_RWSE:
  enable: True
  kernel:
    times_func: range(1,17)
  model: Linear
  dim_pe: 20
  raw_norm_type: BatchNorm
pretrained:
  dir: /home/reza/research/results/GraphGPS/pretrained/pcqm4m-GPS+RWSE.deep
  reset_prediction_head: False
train:
  auto_resume: false
  mode: custom
  batch_size: 16
  eval_period: 1
  ckpt_period: 100
  ckpt_best: true
model:
  type: GPSModel
  loss_fun: mse
  edge_decoding: dot
  graph_pooling: mean
gt:
  layer_type: CustomGatedGCN+Transformer
  layers: 16
  n_heads: 8
  dim_hidden: 256  # `gt.dim_hidden` must match `gnn.dim_inner`
  dropout: 0.1
  attn_dropout: 0.1
  layer_norm: False
  batch_norm: True
prefix:
  enable: True
  prefix_projection: False
  pre_seq_len: 150
gnn:
  head: san_graph
  layers_pre_mp: 0
  layers_post_mp: 3  # Not used when `gnn.head: san_graph`
  dim_inner: 256  # `gt.dim_hidden` must match `gnn.dim_inner`
  batchnorm: True
  act: gelu
  dropout: 0.0
  agg: mean
  normalize_adj: False
optim:
  clip_grad_norm: True
  optimizer: adamW
  weight_decay: 1e-5
  base_lr: 0.001
  max_epoch: 200
  scheduler: cosine_with_warmup
  num_warmup_epochs: 5

