out_dir: /home/reza/research/results/GraphGPS/gine-metstab-finetune
metric_best: auc
accelerator: cuda
devices: 1
wandb:
  use: false
  project: metstab
dataset:
  cache_load: true
  cache_save: true
  dir: /home/reza/research/data/GraphGPS/
  format: PyG
  name: Moleculenet-Metstab
  split_mode: cv-kfold-5
  split_dir: /home/reza/research/data/GraphGPS/splits/
  task: graph
  task_type: classification_multilabel
  resample_negative: True
  transductive: False
  node_encoder: True
  node_encoder_name: SimpleAtom
  node_encoder_bn: False
  edge_encoder: True
  edge_encoder_name: SimpleBond
  edge_encoder_bn: False
train:
  mode: custom
  batch_size: 32
  eval_period: 1
  ckpt_period: 100
  ckpt_best: true
model:
  type: custom_gnn
  loss_fun: cross_entropy
  edge_decoding: dot
  graph_pooling: mean
gnn:
  head: inductive_node
  layers_pre_mp: 0
  layers_mp: 8
  layers_post_mp: 2
  dim_inner: 256
  layer_type: gineconv
  act: relu
  residual: True
  agg: mean
  dropout: 0.1
  normalize_adj: False
optim:
  optimizer: adamW
  weight_decay: 1e-5
  base_lr: 0.004
  max_epoch: 50
  scheduler: reduce_on_plateau
  reduce_factor: 0.5
  schedule_patience: 5
  min_lr: 1e-5
